### ISSUE TITLE
Saving results of TE Computation

### ISSUE THREAD

**Issue by mgkabadi** [trentool/TRENTOOL3#14]
Dear Contributors,
I' am using TRENTOOL on Process Data for directed graph modeling (causality).
I used a previous version of the toolbox and results for each prediction step u was saved correctly (see screenshot 1)
But when i update the Toolbox only 2 results are saved (see attachment 2).
Can you help me to solve this issue.
The intermediate results are useful for plotting TE in function of prediction step u
Best Regards,
![1 previous trentool version on lorenzdata example](https://cloud.githubusercontent.com/assets/5683468/8894767/9aab22f6-33c2-11e5-899b-008811b49c1f.PNG)
![2](https://cloud.githubusercontent.com/assets/5683468/8894771/a38014d6-33c2-11e5-8cfa-9ccb224a31d6.PNG)

**Comment by mgkabadi** [comment]
I find a solution for the issue.
The section was commented for saving intermediate results but this change was not traced.
![salution_commented_section _on_tesurrogatestats](https://cloud.githubusercontent.com/assets/5683468/8894830/9486f95c-33c4-11e5-8598-9c33e3689c0b.png)

**Comment by pwollstadt** [comment]
Dear mgkababadi,

you are right, TRENTOOL does not save intermediate results anymore. This is a fix of an open issue (see [TEfindDelay.m shouldn't save TEpermtest as temporary result #1](https://github.com/trentool/TRENTOOL3/issues/1)), since these intermediate files do not contain anything but the intermediate TE estimates (using different assumed values for the delay u) and no statistics, we considered them obsolete. 

You are right, that these intermediate TE values are useful for plotting. The values are still kept in the output structure and we also changed the plotting function `InteractionDelayReconstruction_plotting.m` to work with the new output. I am currently traveling, but I will upload a release version of TRENTOOL with a documentation of these changes as soon as possible.

Best, Patricia

**Comment by trentool** [comment]
@mgkabadi the new release version of TRENTOOL3 is now [online](https://github.com/trentool/TRENTOOL3/releases/tag/v3.4.2). I will close this issue.
