### ISSUE TITLE
Unable to save Lorenzdata in example_script_CPUmethod

### ISSUE THREAD

**Issue by jpainam** [trentool/TRENTOOL3#30]
Hi, I'm trying to run the code in `example_script_CPUmethod.m` but end up with this error.
```
Error using save
Unable to write file results\Lorenzdata_1->2__RAG4_TGA_opt_us_TEpermtest_output.mat: Invalid argument.
```
I tried to change the directory, but it still doesn't work.

Thank you

**Comment by pwollstadt** [comment]
Hi @jpainam, could you post the save command you are using? Do you provide the file name with or without the '.mat' extension? This could be an issue, see for example [here](https://www.mathworks.com/matlabcentral/answers/296384-my-code-wont-run-due-to-invalid-argumument).

**Comment by jpainam** [comment]
Hi, removing these special characters `1->2__` from the filename solved the problem. But now I have another problem. 
`TRENTOOL ERROR: You requested ensemble method with GPU calculation. No Nvidia GPU could be detected on your system.`
How can I avoid using my GPU? I'm running `example_script_ensemblemethod.m`
I'm using Windows.

**Comment by mwibral** [comment]
Hi Jean-Paul,

to avoid using the GPU you would have to shift from the ensemble method 
to the older standard method. This is because the computations of the 
ensemble method are so demanding that execution on CPU will potentially 
have to wait for a very long time, hence they were not implemented. 
However, we strongly recommend to use the ensemble method as it makes 
better use of the data.

If you're familiar with python you may want to have a look at IDTxl 
(https://github.com/pwollstadt/IDTxl, which is sort of a spiritual 
successor to trentool), there the ensemble method would be available as 
a CPU-based version, and also as an OpenCL version for AMD or NVIDIA GPUs.

Best,

Michael

**Comment by jpainam** [comment]
Thanks @mwibral I'll try [https://github.com/pwollstadt/IDTxl](https://github.com/pwollstadt/IDTxl) as I'm already familiar with python.
